### ISSUE TITLE
Unexpected characters - even in the simplest scenario

### ISSUE THREAD

**Issue by jbotorek** [FasterXML/aalto-xml#49]
Hello,
I am new to the "world" of aalto. Unfortunately, I am not able to make it run as expected - It keeps returning _com.fasterxml.aalto.WFCException_ , even in the simplest scenario (e.g. http://www.cowtowncoder.com/blog/archives/2011/03/entry_451.html this old blog entry).
Here is my code:

`byte[] XML = "<tag>Tove</tag>".getBytes();`
`AsyncXMLInputFactory xmlInputFactory = new InputFactoryImpl();`
`AsyncXMLStreamReader<AsyncByteArrayFeeder> asyncReader = xmlInputFactory.createAsyncFor(XML);`
   ` int inputPtr = 0;`
`int type;`
`do {`
	`while ((type = asyncReader.next()) == AsyncXMLStreamReader.EVENT_INCOMPLETE) {`
		`asyncReader.getInputFeeder().feedInput(XML, inputPtr++, 1);`
		`if (inputPtr >= XML.length) { `
			`asyncReader.getInputFeeder().endOfInput();`
		`}`
	`}`
	`System.out.println("Got event of type: "+type);`
`} while (type != XMLEvent.END_DOCUMENT);`
`asyncReader.close();`

It keeps mi returning: 
_com.fasterxml.aalto.WFCException: Unexpected character 't' (code 116) in epilog (unbalanced start/end tags?)_

Do you know, how to _feedInput_ to the _feeder_ so that no Exception is thrown, please? What do I do wrong?

I utilize com.fasterxml.aalto-xml in the version 1.0.0.

Thank you for any help

**Comment by cowtowncoder** [comment]
Ok. So, the problem here is that you are feeding the same input twice: first via `createAsyncFor()`, and then also byte-by-byte in loop. Error message is bit vague, and it really should try to explain the issue better (it is trying to see if we get a comment or processing instruction -- which would be valid -- but instead would get a tag which is illegal, as only single root is allowed).
I'll file a separate issue for better error message.

So: either pass input document in when construction, or feed it in chunks, but not both.

The other minor thing is that end marker should be indicated separately from feeding the last byte (otherwise the last byte might not be read). But I don't know if that causes problems here.

**Comment by aamalik** [comment]
@cowtowncoder can you write correct code for it. I have been trying for a long time and I can find good documentation.

**Comment by cowtowncoder** [comment]
@aamalik Same problem here: please read my explanation. It is frustrating to be asked again after fully explaining the issue. And if you do not understand the issue, ask question about which part is specifically problematic.
